#!/usr/bin/env bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

prebuild() {
	mkdir -p assets/{static,content}
	cp static/* assets/static/
	sass --source-map --embed-source-map styles/:assets/static/
	chmod -R a+r assets/
}

if [ "$1" == "run" ];
then
	rm -r assets/static
	prebuild
	export $(cat .env | grep -v '^#' | xargs)
	go run -ldflags "-X main.version=$(git rev-parse --short HEAD)" .
elif  [ "$1" == "build" ];
then
	prebuild
	go build -o vigo360 -ldflags "-X main.version=$(git rev-parse --short HEAD)" .
	echo "Asegúrate de que /static en NGINX apunte a assets/"
else
	printf "Vigo360 launcher script\nusage: ${0} [command]\n\n	build: compiles vigo360 to a binary to be ran in production\n	  run: runs vigo360 via in memory.\n"
fi